#!/bin/sh

# If everything including com is in ShephardsPlayApplet.jar,
# then can run it standalone with no classpath
#exec java -jar ShephardsPlayApplet.jar "$@"

# Have to do it this way if com is not in ShephardsPlayApplet.jar
#exec java -classpath "ShephardsPlayApplet.jar;donhatchsw.jar" ShephardsPlayApplet "$@"

# This way doesn't require jar to be made at all, just the class files
#exec java -classpath ".;donhatchsw.jar" ShephardsPlayApplet "$@"

# Requires neither jar nor donhatchsw to be made
exec java -classpath ".;../donhatchsw/myGitRepo" ShephardsPlayApplet "$@"
