#!/bin/bash

# Classpath separator.
# Cygwin: ';' only  (I think)
# Linux: ':' only (openjdk-8 at least)
# Darwin: ':' only
# Darwin and Linux both have uname, so that's a good differentior from Cygwin.
# XXX hmm according to Makefile, cygwin does have uname, and it outputs "Cygwin"?  so I'm not sure this will work.  should use logic in Makefile probably.
uname && sep=':' || sep=';'

# If everything including com is in ShephardsPlayApplet.jar,
# then can run it standalone with no classpath
#exec java -jar ShephardsPlayApplet.jar "$@"

# Have to do it this way if com is not in ShephardsPlayApplet.jar
#exec java -classpath "ShephardsPlayApplet.jar${sep}donhatchsw.jar" ShephardsPlayApplet "$@"

# This way doesn't require jar to be made at all, just the class files
#exec java -classpath ".${sep}donhatchsw.jar" ShephardsPlayApplet "$@"

# Requires neither jar nor donhatchsw to be made (note that we still *compile* out of donhatchsw.jar in current directory though... this is just useful for non-interface fixes or debugging in donhatchsw)
exec java -classpath ".${sep}../donhatchsw" ShephardsPlayApplet "$@"
